config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'pages#home'
  get "about" => "pages#about"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  def index
    @pins = Pin.all
  end


  def show
  end


  def new
    @pin = current_user.pins.build
  end


  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Pin was successfully created."
    else
      render action: "new"
    end
  end
  
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was successfully updated."
    else
      render action: "edit"
    end
  end
  
  def destroy
    @pin.destroy
    redirect_to pins_url
  end
  
  private
  
  def set_pin
    @pin = Pin.find(params[:id])
  end
  
  def correct_user
    @pin = current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: "Not authorized to edit this page" if @pin.nil?
  end
  
  def pin_params
    params.require(:pin).permit(:description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
	<div class="container">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
		<span class="sr-only">Toggle Navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="#">Iphinteresting</a>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
	<ul class="nav navbar-nav navbar-right">
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
    <% if user_signed_in? %>
		<li><%= link_to new_pin_path do %>
			<span class="glyphicon glyphicon-plus"></span>New Pin
			<% end %>
		</li>
    <li><%= link_to "Account Settings", edit_user_registration_path %></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <% end %>
	</ul>
</div><!-- /.navbar-collapse -->
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-#{name}")  %>
  <% end %>
	<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>We are working on our One Month Rails Pinteresting App</p>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>Welcome to my app!</h1>
  <% if user_signed_in? %>
    #do something
  <% else %>
<p>
  <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>.
</p>
  <% end %> 
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= image_tag pin.image.url(:medium) %>
      <div class="panel-body">
        <%= pin.description %>
        <%= pin.user.email if pin.user %>
        <%= link_to 'Show', pin_path(pin) %>
        <% if pin.user == current_user %>
          <%= link_to 'Edit', edit_pin_path(pin) %>
          <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>
<div class="row">
  <div class="col-md-offset-2 col-md-8"
    <div class="panel panel-default">
      <%= image_tag @pin.image.url(:medium) %>
    </div>
    <div class="panel-body">
      <p><%= @pin.description %></p>
      <p><strong><%= @pin.user.email if @pin.user %></strong></p>

      <% if @pin.user == current_user %>
        <%= link_to 'Edit', edit_pin_path(@pin) %>
      <% end %>

    </div>
  </div>
</div>
</div>